name: Validate Artifacts

on:
  push:
  # branches:
  # - master
  pull_request:
    types:
      - closed
    branches:
      - master
  release:
    types:
      - created

jobs:
  validate_scw_artifact:
    name: Validate SCW Artifact
    runs-on: ubuntu-latest
    if: github.event.pull_request == null || github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lib/requirements.txt
      - name: Install requests library
        run: |
          pip install requests
      - name: Create artifact json file
        run: |
          python3 -B lib/generate_artifacts.py
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Secure Code Warrior Links
          path: scw_links.json
      - name: Validate links
        run: |
          python3 -B lib/validate_artifacts.py
